out_dir: '03b_model/out'

run_id: 'Run_49'  

inputs: ['discharge_01463500', 
                #'specific_conductance_01463500',
                'discharge_01474500', 
                #'specific_conductance_01474500', 
                'wl_range_8557380','wl_max_8557380','wl_obs_pred_8557380','wl_filtered_8557380',
                'air_pressure_delsjmet', 
                'temperature_delsjmet',
                #'precipitation_delsjmet',
                'wind_direction_delsjmet',
                'wind_speed_delsjmet']#,'wind_speed_direction_delsjmet']                    


#the sinks to be analyzed, this will likely be the salt front location
target: 'saltfront7_weekly'
replicates: 5

#explicitly including summary antecedant data
#window_size and antecedant_variables must be in a list
#as they are iterated over
include_antecedant_data: False
window_size: [60]
antecedant_variables: ['discharge']

#include lagged input only for discharge
include_lagged_input: True
lag: [7,8]


#set the seed for reproducibility for a single model run
#if replicates are run using the run_replicates function
#then the seed is set within the run_replicates function
#as the iterator within each replicate loop
#this ensures that each replicate is unique, but reproducible
seed_set: True
seed: 24

#select the split dates
train_start_date: '2001-01-01'
train_end_date: '2015-12-31'
val_start_date: '2016-01-01'
val_end_date: '2021-06-30'
test_start_date: '2016-01-01'
test_end_date: '2021-06-30'

#model parameters
seq_len: 365
offset: 1
hidden_units: 5
learn_rate: 0.003
recur_dropout: 0.1
dropout: 0.3
n_epochs: 500





